name: Flutter CI Build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Ensures Java compatibility
          java-version: '11'

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses/android-sdk-license

      - name: Build APK with Docker
        run: |
          docker run --rm -v "$PWD":/app -w /app cirrusci/flutter:3.19.0 flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk