name: Flutter Android CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses/android-sdk-license

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v "$PWD":/app \
            -w /app \
            -e ANDROID_SDK_ROOT=/opt/android-sdk-linux \
            cirrusci/flutter:3.19.0 \
            bash -c "flutter pub get && flutter build apk --release"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5